[WIP] Squash history
bdionne/protege-server pull request #7
Opened 2017-05-06 00:56 UTC by AnthonyMl

TODO:
- remove project names from history files and snapshots

2017-05-08 14:10 UTC, bdionne commented
This is good progress! I built this, the client, and the revision diff plugin and it pretty much works as intended. Some TODOs I see:

- the `.history` file also has a backup, that needs to be cleaned up as well

- caching. The server caches the history files that have been opened up, mainly to speed up access to the `HEAD` revision number. The cache entry for the file being squashed needs to be purged, other wise the history still appears even if the client logs out and back in.

- progress indicator. We'll need something like the progress bar we use for Lucene indexing, to indicate progress, otherwise the user has no idea what's going on.

- client. This is probably the major item, the clients need to know that the current snapshot they have locally is out of date

- testing. We definitely will need client/server integration tests for this as it's a major change in core functionality.

- migration. Putting this here for completion, I don't think we'll need to do anything and we can probably get away with a one time manual process as the user base is small, but we should discuss anyhow.

2017-05-09 01:01 UTC, AnthonyMl commented
This commit should address point 1 and 2.
I'm not very satisfied with this solution. The problem is that the caching mechanism goes very deep in one of the Undertow ```RoutingHandler```s (```HTTPChangeService```) while the snapshot stuff goes in the other (```MetaprojectHandler```). It seems Undetow does not allow the same http call to get handled by two handlers so unless we do what we have here we would need some communication between the two handlers (events?) or sharing of the caching pool (which seems pretty heavyweight). Any suggestions are welcome.
@bdionne does this address the caching point above or is there some more done elsewhere?

2017-05-09 01:04 UTC, AnthonyMl commented
Regarding point 3 and 5 (progress indicator and testing): do we want these in the same PR (or group of PRs since it would involve the protege-client-server-integration-tests project) or could we do them separately?

2017-05-09 11:54 UTC, bdionne commented
This looks reasonable, though it doesn't quite work yet, even if the client closes and reopens the app. The history that was squashed is still there, I suspect in the cache. If I recall, Undertow is designed to allow chaining, it's controlled by the return value from each handler. It seems like this squashing is reasonable to have in the changes handler, I'll give it some more thought.

With respect to the tasks, the progress indicator can be handled in a separate PR, but I'd like to have good test coverage before we merge these changes.

2017-05-22 03:00 UTC, rgrinberg requested changes
Looks good. Just a couple of questions

2017-05-22 03:00 UTC, rgrinberg commented on src/main/java/org/protege/editor/owl/server/api/ServerLayer.java
> +            if (outputStream != null) {
tWhy do you have this null check here? Seems like it will never be a null unless you assign a null explicitly to it

2017-05-22 03:00 UTC, rgrinberg commented on src/main/java/org/protege/editor/owl/server/versioning/api/HistoryFile.java
> +            filepath = filepath + FILENAME;
Java8 has a path API now. See https://docs.oracle.com/javase/tutorial/essential/io/pathOps.html

2017-05-23 22:41 UTC, AnthonyMl commented on src/main/java/org/protege/editor/owl/server/versioning/api/HistoryFile.java
> +            filepath = filepath + FILENAME;
Kept it mostly how it was.
I'll check it out.

2017-05-23 22:45 UTC, AnthonyMl commented
There is a bug in the squashing functionality where after squashing on update the client provides an out of date history revision (>0). Still need to fix this for the merge.
@bdionne
Is there a better place to put the http custom header and error code?

2017-05-24 10:51 UTC, bdionne commented
This is looking pretty good, I've been looking into this autoupdate code (issues with deadlocks) and I think I suspect the bug you're running into. After you squash and produce a new snapshot, the other clients still have a `HEAD` revision that's greater than the new `HEAD` on the server.

I"m pretty sure it's a safe bet that the local `HEAD` should never be greater than the remote *unless* a new snapshot has been made.

2017-05-25 18:44 UTC, AnthonyMl commented
That is exactly the problem.
In the case where this client is the one who made the snapshot however the client already has the new snapshot so doing the whole re-opening seems a bit heavyweight so I have been looking into doing without that but instead setting the correct state manually (which would include resetting the local HEAD revision).

2017-05-30 16:57 UTC, rgrinberg requested changes

2017-05-30 16:57 UTC, rgrinberg commented on src/main/java/org/protege/editor/owl/server/api/ServerLayer.java
> +    public String getHistoryFilePath(ProjectId projectId) {
Can you add a NonNull annotation to projectId here?

2017-05-30 16:57 UTC, rgrinberg commented on src/main/java/org/protege/editor/owl/server/api/ServerLayer.java
> +    public void saveProjectSnapshot(SnapShot snapshot, ProjectId projectId, OutputStream responseStream)
NonNull on the projectId please

2017-05-30 16:57 UTC, rgrinberg commented on src/main/java/org/protege/editor/owl/server/api/ServerLayer.java
> +    private File getSnapShotFile(ProjectId projectId) {
NonNull on projectId

2017-05-30 16:57 UTC, rgrinberg commented on src/main/java/org/protege/editor/owl/server/change/ChangeDocumentPool.java
> +    public synchronized void clearHistoryCacheEntry(HistoryFile historyFile) {
NonNull

2017-05-30 16:57 UTC, rgrinberg commented on src/main/java/org/protege/editor/owl/server/http/handlers/HTTPChangeService.java
> +		ProjectId projectId = (ProjectId) ois.readObject();
Since this is user input, I think you should probably verify it. I.e. check that projectId isn't null here.

2017-06-05 00:54 UTC, rgrinberg commented
Note that this PR (or perhaps the client one) breaks pellet pretty badly. The IRI's are no longer reachable in the pellet tests due to this.

2017-06-05 10:19 UTC, bdionne commented
looking at this a bit in the debugger I'm not not sure the missing ontology IRI is the culprit. `ProtegeOntologyState` is failing to load the snapshot, and swallowing the null pointer exception it gets. Pretty easy to see running the pellet server in the debugger.

2017-06-08 09:58 UTC, bdionne commented on src/main/java/org/protege/editor/owl/server/http/handlers/HTTPChangeService.java
> +		if (HTTPServer.server().isPaused()
This is incorrect, this should be an `||` not and `&&`

2017-06-08 10:01 UTC, bdionne commented on src/main/java/org/protege/editor/owl/server/http/handlers/HTTPChangeService.java
> +
Not sure I buy this premature refactoring. This enum incorporates two pieces of state that are used together in one place along one application path.

2017-06-08 10:02 UTC, bdionne commented on src/main/java/org/protege/editor/owl/server/http/handlers/HTTPChangeService.java
> +			&& (requestPath.equals(ServerEndpoints.COMMIT) || requestPath.equals(ServerEndpoints.SQUASH))) {
I see, this is correct, ignore my earlier comment about breaking this logic

2017-06-08 14:05 UTC, rgrinberg commented
Well the point isn't to make the code pretty. The point is to have a decent
error message when an operation fails during the paused state. I've wasted
quite a bit of time figuring that out already.

I tried doing it in less invasive ways before but it was even uglier with
lots of temporary variables getting mutated.

I wouldn't worry so much about the breakage because I added an extensive
test suite to all of this. That being said I can always add more since now
I can just easily unit test the new code too

On Thu, Jun 8, 2017, 6:02 AM Bob Dionne <notifications@github.com> wrote:

> *@bdionne* commented on this pull request.
> ------------------------------
>
> In
> src/main/java/org/protege/editor/owl/server/http/handlers/HTTPChangeService.java
> <https://github.com/bdionne/protege-server/pull/7#discussion_r120847121>:
>
> > @@ -118,8 +118,7 @@ private void handlingRequest(HttpServerExchange exchange)
>  		}
>
>  		if (HTTPServer.server().isPaused()
> -			&& requestPath.equals(ServerEndpoints.COMMIT)
> -			&& requestPath.equals(ServerEndpoints.SQUASH)) {
> +			&& (requestPath.equals(ServerEndpoints.COMMIT) || requestPath.equals(ServerEndpoints.SQUASH))) {
>
> I see, this is correct, ignore my earlier comment about breaking this logic
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/bdionne/protege-server/pull/7#pullrequestreview-42844017>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAIe--Gp8vZAfKU9qfqDyumsx4bx2opeks5sB8algaJpZM4NSkCm>
> .
>

2017-06-08 22:43 UTC, merged